library:
  join: underscore-awesomer.js
  compress: true
  files:
    - src/**/*.coffee

tests:
  output: build
  directories:
    - test/core
    - test/packaging
  modes:
    build:
      bundles:
        test/packaging/build/bundle-latest.js:
          underscore: underscore
          underscore-awesomer: underscore-awesomer.js
        test/packaging/build/bundle-legacy.js:
          underscore: vendor/underscore-1.2.1.js
          underscore-awesomer: underscore-awesomer.js
      no_files_ok: ['test/packaging']
    test:
      command: phantomjs
      runner: phantomjs-qunit-runner.js
      files:
        - '**/*.html'

postinstall:
  commands:
    - 'cp underscore vendor/underscore-latest.js'