library:
  join: underscore-awesomer.js
  compress: true
  files:
    - src/**/*.coffee

tests:
  output: build
  directories:
    - test/core
    - test/packaging
  options:
    test:
      command: phantomjs
      runner: phantomjs-qunit-runner.js
      files:
        - '**/*.html'
    build:
      no_files_ok: ['test/core', 'test/packaging']

postinstall:
  copy_latest_underscore:
    command: 'cp'
    args: ['underscore', 'vendor/underscore-latest.js']